using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CreatureCreator.Core.Enums
{
    public enum ChrModels
    {
        Unknown = 0,
        HumanMale = 1,
        HumanFemale = 2,
        OrcMale = 3,
        OrcFemale = 4,
        DwarfMale = 5,
        DwarfFemale = 6,
        NightElfMale = 7,
        NightElfFemale = 8,
        UndeadMale = 9,
        UndeadFemale = 10,
        TaurenMale = 11,
        TaurenFemale = 12,
        GnomeMale = 13,
        GnomeFemale = 14,
        TrollMale = 15,
        TrollFemale = 16,
        GoblinMale = 17,
        GoblinFemale = 18,
        BloodElfMale = 19,
        BloodElfFemale = 20,
        DraeneiMale = 21,
        DraeneiFemale = 22,
        FelOrcMale = 23,
        FelOrcFemale = 24,
        NagaMale = 25,
        NagaFemale = 26,
        BrokenMale = 27,
        BrokenFemale = 28,
        SkeletonMale = 29,
        SkeletonFemale = 30,
        VrykulMale = 31,
        VrykulFemale = 32,
        TuskarrMale = 33,
        TuskarrFemale = 34,
        ForestTrollMale = 35,
        ForestTrollFemale = 36,
        TaunkaMale = 37,
        TaunkaFemale = 38,
        NorthrendSkeletonMale = 39,
        NorthrendSkeletonFemale = 40,
        IceTrollMale = 41,
        IceTrollFemale = 42,
        WorgenMale = 43,
        WorgenFemale = 44,
        GilneanMale = 45,
        GilneanFemale = 46,
        PandarenMale = 47,
        PandarenFemale = 48,
        // ??
        NightborneMale = 53,
        NightborneFemale = 54,
        HighmountainTaurenMale = 55,
        HighmountainTaurenFemale = 56,
        VoidElfMale = 57,
        VoidElfFemale = 58,
        LightforgedDraeneiMale = 59,
        LightforgedDraeneiFemale = 60,
        ZandalariMale = 61,
        ZandalariFemale = 62,
        KulTiranMale = 63,
        KulTiranFemale = 64,
        ThinHumanMale = 65,
        ThinHumanFemale = 66,
        DarkIronDwarfMale = 67,
        DarkIronDwarfFemale = 68,
        VulperaMale = 69,
        VulperaFemale = 70,
        MagharOrcMale = 71,
        MagharOrcFemale = 72,
        MechagnomeMale = 73,
        MechagnomeFemale = 74
    }
}
